### ISSUE TITLE
How I use it? 

### ISSUE THREAD

**Issue by dv9** [louy/PGOctoShape#1]
thanks for posting this example !. I wanted to know if there is any description of how I use it, I'm developing an app in cordova and visual studio for andoid and ios and requires Octoshape.

Grettings!

**Comment by louy** [comment]
Of course, install it like any other cordova/phonegap plugin. Then in your javascript you should do the following.
- On `deviceready` event call `PGOctoShape.init();`.
- To start a stream use `PGOctoShape.play( url [, successCallback, errorCallback] );`
- To stop the current stream use `PGOctoShape.stop( [successCallback, errorCallback] );`
