### ISSUE TITLE
package octoshape.osa2 does not exist

### ISSUE THREAD

**Issue by diogolmenezes** [louy/PGOctoShape#2]
Hey man, how are u ?

When we run "cordova run android" we get this message " package octoshape.osa2 does not exist"

How can I solve it ? How can i Install the ocoshape SDK ?

**Comment by diogolmenezes** [comment]
Hey man the problem was the namespaces now they are:

import octoshape.osa2.Problem;
import octoshape.osa2.android.StreamPlayer;
import octoshape.osa2.android.OctoshapeSystem;
import octoshape.osa2.listeners.ProblemListener;
import octoshape.osa2.android.listeners.StreamPlayerListener;

But, now i'm getting the follow error, could you help me?

PGOctoShape.java:130: error: <anonymous com.l0uy.phonegap.PGOctoShape$1> is not abstract and does not override abstract method onPortBound(String,int) in OctoshapePortListener
    [javac]                 new OctoshapePortListener() {

**Comment by diogolmenezes** [comment]
Hey man, I did :)

If you want to see the solution take a look 

https://github.com/diogolmenezes/PGOctoShape/blob/master/src/android/PGOctoShape.java

Regards from Brazil

**Comment by louy** [comment]
Hi Diogo,

Sorry I wasn't able to see this earlier. I have abandoned this plugin since it was for a finished project.
Yeah apparently they have changed their plugin's internal structure. I think if anyone faces such problems their documentation would be helpful.

Regards from Syria, 😊
